<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>CrossStitchRework</AssemblyName>
    <RootNamespace>CrossStitchRework</RootNamespace>
    <Version>0.4.2</Version>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>$(BepInExCoreDir)0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="BepInEx.Core">
      <HintPath>$(BepInExCoreDir)BepInEx.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="BepInEx.Unity.Common">
      <HintPath>$(BepInExCoreDir)BepInEx.Unity.Common.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="BepInEx.Unity.Mono">
      <HintPath>$(BepInExCoreDir)BepInEx.Unity.Mono.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(GameManagedDir)Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="PlayMaker">
      <HintPath>$(GameManagedDir)PlayMaker.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="TeamCherry.TK2D">
      <HintPath>$(GameManagedDir)TeamCherry.TK2D.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(GameManagedDir)UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.Physics2DModule">
      <HintPath>$(GameManagedDir)UnityEngine.Physics2DModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(GameManagedDir)UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <Target Name="DeployMod" AfterTargets="Build" Condition="'$(DeployMod)' != 'false'">
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(GameRoot)BepInEx\plugins\" />
  </Target>
</Project>
